M48
; DRILL file {KiCad (6.0.11-0)} date 2023 March 19, Sunday 15:08:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-19T15:08:07+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.4764Y-4.3898
T2
X5.0394Y-4.3504
X5.0394Y-4.8622
X7.0669Y-4.3504
X7.0669Y-4.8622
T0
M30
